.TH "HTTPRequestException" 3 "Wed Apr 8 2020" "Version .." "RESTServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HTTPRequestException
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HTTPRequest\&.hpp>\fP
.PP
Inherits exception\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RESTServer from the source code\&.
