.TH "HTTPRequest" 3 "Wed Apr 8 2020" "Version .." "RESTServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HTTPRequest
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HTTPRequest\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHTTPRequest\fP (const std::string &pMsg)"
.br
.ti -1c
.RI "virtual \fB~HTTPRequest\fP ()"
.br
.RI "The \fBHTTPRequest\fP class destructor\&. "
.ti -1c
.RI "std::string \fBmsg\fP (void) const"
.br
.ti -1c
.RI "std::string \fBmethodStr\fP (void) const"
.br
.ti -1c
.RI "\fBhttpMethod_t\fP \fBmethod\fP (void) const"
.br
.ti -1c
.RI "std::string \fBhttpVersionStr\fP (void) const"
.br
.ti -1c
.RI "\fBhttpVersion_t\fP \fBhttpVersion\fP (void) const"
.br
.ti -1c
.RI "std::string \fBhost\fP (void) const"
.br
.ti -1c
.RI "std::string \fBURL\fP (void) const"
.br
.ti -1c
.RI "std::string \fBuserAgent\fP (void) const"
.br
.ti -1c
.RI "std::string \fBaccept\fP (void) const"
.br
.ti -1c
.RI "std::string \fBacceptLanguage\fP (void) const"
.br
.ti -1c
.RI "std::string \fBacceptEncoding\fP (void) const"
.br
.ti -1c
.RI "std::string \fBreferer\fP (void) const"
.br
.ti -1c
.RI "std::string \fBupgradeInsecureRequest\fP (void) const"
.br
.ti -1c
.RI "std::string \fBheaders\fP (void) const"
.br
.ti -1c
.RI "std::string \fBURI\fP (void) const"
.br
.ti -1c
.RI "std::string \fBquery\fP (void) const"
.br
.ti -1c
.RI "\fBhttpBody_t\fP \fBbody\fP (void) const"
.br
.ti -1c
.RI "std::string \fBpayload\fP (void) const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HTTPRequest::HTTPRequest (const std::string & pMsg)"
@breif The \fBHTTPRequest\fP constructor
.PP
The constructor parses the HTTP request\&.
.PP
\fBParameters\fP
.RS 4
\fIpMsg\fP The received HTTP request
.RE
.PP
\fBExceptions\fP
.RS 4
\fI\fBHTTPRequestException\fP\fP if parsing fails 
.RE
.PP

.SS "HTTPRequest::~HTTPRequest ()\fC [virtual]\fP"

.PP
The \fBHTTPRequest\fP class destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "std::string HTTPRequest::accept (void) const"

.SS "std::string HTTPRequest::acceptEncoding (void) const"

.SS "std::string HTTPRequest::acceptLanguage (void) const"

.SS "\fBhttpBody_t\fP HTTPRequest::body (void) const"

.SS "std::string HTTPRequest::headers (void) const"

.SS "std::string HTTPRequest::host (void) const"

.SS "\fBhttpVersion_t\fP HTTPRequest::httpVersion (void) const"

.SS "std::string HTTPRequest::httpVersionStr (void) const"

.SS "\fBhttpMethod_t\fP HTTPRequest::method (void) const"

.SS "std::string HTTPRequest::methodStr (void) const"

.SS "std::string HTTPRequest::msg (void) const"

.SS "std::string HTTPRequest::payload (void) const"

.SS "std::string HTTPRequest::query (void) const"

.SS "std::string HTTPRequest::referer (void) const"

.SS "std::string HTTPRequest::upgradeInsecureRequest (void) const"

.SS "std::string HTTPRequest::URI (void) const"

.SS "std::string HTTPRequest::URL (void) const"

.SS "std::string HTTPRequest::userAgent (void) const"


.SH "Author"
.PP 
Generated automatically by Doxygen for RESTServer from the source code\&.
