.TH "RESTServer.hpp" 3 "Wed Apr 8 2020" "Version .." "RESTServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RESTServer.hpp \- \fBRESTServer\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <exception>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <string>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBRESTServerException\fP"
.br
.ti -1c
.RI "class \fBRESTServer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBRESTServer\fP class\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for RESTServer from the source code\&.
