.TH "RESTServer.cpp" 3 "Wed Apr 8 2020" "Version .." "RESTServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RESTServer.cpp \- \fBRESTServer\fP class implementation\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'RESTServer\&.hpp'\fP
.br
\fC#include 'HTTPRequest\&.hpp'\fP
.br
\fC#include 'webpages\&.hpp'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <netinet/in\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSERVER_BUFFER_SIZE\fP   4096U"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBRESTServer\fP class implementation\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define SERVER_BUFFER_SIZE   4096U"

.SH "Author"
.PP 
Generated automatically by Doxygen for RESTServer from the source code\&.
