.TH "webpages.hpp" 3 "Wed Apr 8 2020" "Version .." "RESTServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
webpages.hpp
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const char *const \fBhtmlResponseCode200\fP"
.br
.ti -1c
.RI "const char *const \fBhtmlResponseCode400\fP"
.br
.ti -1c
.RI "const char *const \fBhtmlResponseCode404\fP"
.br
.ti -1c
.RI "const char *const \fBhtmlResponseCode500\fP"
.br
.ti -1c
.RI "const char *const \fBhtmlResponseCode501\fP"
.br
.ti -1c
.RI "const char *const \fBhtmlDocType\fP"
.br
.ti -1c
.RI "const char *const \fBhtmlPageBegin\fP"
.br
.ti -1c
.RI "const char *const \fBhtmlPageEnd\fP"
.br
.ti -1c
.RI "const char *const \fBhtmlHead\fP"
.br
.ti -1c
.RI "const char *const \fBhtmlGeneralKenobi\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBRESTServer\fP project 
.SH "Variable Documentation"
.PP 
.SS "const char* const htmlDocType"

.SS "const char* const htmlGeneralKenobi"

.SS "const char* const htmlHead"

.SS "const char* const htmlPageBegin"

.SS "const char* const htmlPageEnd"

.SS "const char* const htmlResponseCode200"

.SS "const char* const htmlResponseCode400"

.SS "const char* const htmlResponseCode404"

.SS "const char* const htmlResponseCode500"

.SS "const char* const htmlResponseCode501"

.SH "Author"
.PP 
Generated automatically by Doxygen for RESTServer from the source code\&.
