.TH "webpages.cpp" 3 "Wed Apr 8 2020" "Version .." "RESTServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
webpages.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'webpages\&.hpp'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const char *const \fBhtmlResponseCode200\fP"
.br
.ti -1c
.RI "const char *const \fBhtmlResponseCode400\fP"
.br
.ti -1c
.RI "const char *const \fBhtmlResponseCode404\fP"
.br
.ti -1c
.RI "const char *const \fBhtmlResponseCode500\fP"
.br
.ti -1c
.RI "const char *const \fBhtmlResponseCode501\fP"
.br
.ti -1c
.RI "const char *const \fBhtmlDocType\fP"
.br
.ti -1c
.RI "const char *const \fBhtmlPageBegin\fP"
.br
.ti -1c
.RI "const char *const \fBhtmlPageEnd\fP"
.br
.ti -1c
.RI "const char *const \fBhtmlHead\fP"
.br
.ti -1c
.RI "const char *const \fBhtmlGeneralKenobi\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBRESTServer\fP project 
.SH "Variable Documentation"
.PP 
.SS "const char* const htmlDocType"
\fBInitial value:\fP
.PP
.nf
= R"=====(<!DOCTYPE html>
)====="
.fi
.SS "const char* const htmlGeneralKenobi"
\fBInitial value:\fP
.PP
.nf
= R"=====(
    <html lang ="en">
        <head>
            <title>web-example</title>
        </head>
        <body>
            - Hello there !
            - General Kenobi !
        </body>
    </html>
)====="
.fi
.SS "const char* const htmlHead"
\fBInitial value:\fP
.PP
.nf
= R"=====(
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" href="data:,">
        <style>
        html {
            font-family: Helvetica;
            display: inline-block;
            margin: 0px auto;
            text-align: center;
        }
        \&.button {
            background-color: #195B6A;
            border: none;
            color: white;
            padding: 16px 40px;
            text-decoration: none;
            font-size: 30px;
            margin: 2px;
            cursor: pointer;
        }
        \&.button2 {
            background-color: #77878A;
        }
        </style>
    </head>
)====="
.fi
.SS "const char* const htmlPageBegin"
\fBInitial value:\fP
.PP
.nf
= R"=====(<html lang="en">
)====="
.fi
.SS "const char* const htmlPageEnd"
\fBInitial value:\fP
.PP
.nf
= R"=====(</html>

)====="
.fi
.SS "const char* const htmlResponseCode200"
\fBInitial value:\fP
.PP
.nf
= R"=====(HTTP/1\&.1 200 OK
Content-type:text/html
Connection: close
)====="
.fi
.SS "const char* const htmlResponseCode400"
\fBInitial value:\fP
.PP
.nf
= R"=====(HTTP/1\&.0 400 BAD REQUEST
Content-Type: text/html
Connection: close

<!DOCTYPE html>
<html lang ="en">
    <head>
        <title>400 - BAD REQUEST</title>
    </head>
    <body>
        Your browser sent a bad request, 
        such as a POST without a Content-Length\&.
    </body>
</html>
)====="
.fi
.SS "const char* const htmlResponseCode404"
\fBInitial value:\fP
.PP
.nf
= R"=====(HTTP/1\&.0 404 NOT FOUND
Content-Type: text/html
Connection: close

<!DOCTYPE html>
<html lang ="en">
    <head>
        <title>404 - Not found</title>
    </head>
    <body>
        The server could not fulfill your request because the resource specified"
        is unavailable or nonexistent\&.
        <br>"
            Please check that you entered the correct URL\&.
        </br>
    </body>
</html>
)====="
.fi
.SS "const char* const htmlResponseCode500"
\fBInitial value:\fP
.PP
.nf
= R"=====(HTTP/1\&.0 500 Server internal error
Content-Type: text/html
Connection: close

<!DOCTYPE html>
<html lang ="en">
    <head>
        <title>500 - Server internal error</title>
    </head>
    <body>
        Server-side error prohibited execution\&.
    </body>
</html>
)====="
.fi
.SS "const char* const htmlResponseCode501"
\fBInitial value:\fP
.PP
.nf
= R"=====(HTTP/1\&.1 501 Method Not Implemented
Content-type:text/html
Connection: close

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>
            501 - Method Not Implemented
        </title>
    </head>
    <body>
        HTTP request method not supported\&.
    </body>
</html>
)====="
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for RESTServer from the source code\&.
